version: "3.7"

services:
  GEDDO:
    image: nuxt
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: site_GEDDO
    restart: always
    volumes:
      - ./src:/GEDDO/src:rw
    ports:
      - "3000:3000"
